apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example-root-password
            - name: MYSQL_DATABASE
              value: example-wordpress
            - name: MYSQL_USER
              value: example-wp_user
            - name: MYSQL_PASSWORD
              value: example-password
          ports:
            - containerPort: 3306
